image: docker:19.03.11

services:
  - docker:dind


stages:
  - build
  - test
  - review
  - deploy
  - production
  - cleanup


variables:
  AUTO_DEVOPS_PLATFORM_TARGET: ECS

include:
  - template: Jobs/Build.gitlab-ci.yml
  - template: Jobs/Deploy/ECS.gitlab-ci.yml


build:
  stage: build

  rules:
    - if: '$CI_BUILD_REF_NAME == "staging"' 
    - if: '$CI_COMMIT_TAG == "review"'

  script:
    - if [ $CI_BUILD_REF_NAME == "staging" ]; then REGISTERY_END_POINT="staging"; else REGISTERY_END_POINT="review"; fi
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t registry.gitlab.com/alakine-dashboard/alakine-be/${REGISTERY_END_POINT} .
    - docker push registry.gitlab.com/alakine-dashboard/alakine-be/${REGISTERY_END_POINT}


test:
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-ecs:latest
  stage: test

  script:
    - echo "TODO"


review_ecs:
  stage: review
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-ecs:latest
  rules:
    - if: '$CI_COMMIT_TAG == "not-implemented"'
  script:
    - echo "TODO"


deploy_review:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-ecs:latest
  rules:
    - if: '$CI_COMMIT_TAG == "review"'
  script:
    - aws ecs update-service --force-new-deployment --cluster $CI_AWS_ECS_CLUSTER --service $CI_AWS_ECS_SERVICE
  variables:
    CI_AWS_ECS_CLUSTER: alakine-fregate-2
    CI_AWS_ECS_SERVICE: alakine-backend-dev
    AWS_REGION: eu-west-3 


deploy_staging:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-ecs:latest
  only:
   - staging
  script:
    - aws ecs update-service --force-new-deployment --cluster $CI_AWS_ECS_CLUSTER --service $CI_AWS_ECS_SERVICE
  variables:
    CI_AWS_ECS_CLUSTER: alakine-fregate-2
    CI_AWS_ECS_SERVICE: alakine-backend-staging-2
    AWS_REGION: eu-west-3


deploy:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-ecs:latest
  only:
   - master
  script:
    - echo "TODO"
  variables:
    CI_AWS_ECS_CLUSTER: not-defined
    CI_AWS_ECS_SERVICE: not-defined
    AWS_REGION: not-defined


