from typing import Optional

from pydantic.fields import Field

from core.utils.str_enum import StrEnum
from web.core.results import CamelModel


class CredentialStatusEnum(StrEnum):
    VERIFIED = "Verified"
    NOT_EXISTS = "NotExists"
    MULTIPLE_WORKSPACES = "MultipleWorkspaces"

    REQUIRE_VERIFICATION = "RequireVerification"
    REQUIRE_CODE = "RequireCode"
    REQUIRE_CHANGE_PASSWORD = "RequireChangePassword"

    TOKEN_INVALID = "TokenInvalid"
    TOKEN_EXPIRED = "TokenExpired"

    CODE_DOESNT_MATCH = "CodeDoesntMatch"
    CODE_EXPIRED = "CodeExpired"


class MobileAuthCreatePasswordIn(CamelModel):
    password: str = Field(example="pass")
    updated_verification_token: str = Field(example="05a7f2e7b2e6f7e3171bdad41af2ea11745059e3")


class MobileAuthCreatePasswordOut(CamelModel):
    credential_status: str = Field(
        example=f"{CredentialStatusEnum.VERIFIED} | {CredentialStatusEnum.TOKEN_INVALID}")


class MobileAuthVerifyUsernameIn(CamelModel):
    username: str = Field(example="email | phone_number")
    reset: bool = Field(example=False)


class MobileAuthVerifyUsernameOut(CamelModel):
    status: str = Field(example=f"{CredentialStatusEnum.VERIFIED} | "
                                f"{CredentialStatusEnum.REQUIRE_CODE} | "
                                f"{CredentialStatusEnum.REQUIRE_VERIFICATION} | "
                                f"{CredentialStatusEnum.REQUIRE_CHANGE_PASSWORD} |"
                                f"{CredentialStatusEnum.CODE_DOESNT_MATCH} | "
                                f"{CredentialStatusEnum.TOKEN_EXPIRED}")

    # verificationToken - temporary token generated by Server just for verification process
    verification_token: Optional[str]


class MobileAuthVerifyCode(CamelModel):
    code: str = Field(example="1234")
    verification_token: str = Field(example="05a7f2e7b2e6f7e3171bdad41af2ea11745059e3")


class MobileAuthVerifyCodeOut(CamelModel):
    status: str = Field(example=f"{CredentialStatusEnum.CODE_DOESNT_MATCH} | "
                                f"{CredentialStatusEnum.REQUIRE_CHANGE_PASSWORD} |"
                                f"{CredentialStatusEnum.TOKEN_INVALID} | "
                                f"{CredentialStatusEnum.TOKEN_EXPIRED}")

    # verificationToken - temporary token generated by Server just for verification process
    updated_verification_token: Optional[str]


class SignInResponse(CamelModel):
    id_token: str
    access_token: str
    refresh_token: str
    username: str


class UserInfoResult(CamelModel):
    user_pool_id: Optional[str]
    username: Optional[str]
    email: Optional[str]
    phone_number: Optional[str]
    sub: Optional[str]
    enabled: Optional[bool]
    status: Optional[str] = Field(
        example=("UNCONFIRMED | CONFIRMED | ARCHIVED | COMPROMISED | UNKNOWN |"
                 " RESET_REQUIRED | FORCE_CHANGE_PASSWORD")
    )
